name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -R # Per elencare tutti i file e le cartelle

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Change directory to Progetto_TPSIT_finale
        run: cd Progetto_TPSIT_finale

      - name: Build with Maven
        run: mvn -B package